services:
  backend:
    build: ./PaymentSystem
    container_name: Payment_System
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./PaymentSystem:/app
    env_file:
      - PaymentSystem/.env
    ports:
      - "8000:8000"
    restart: unless-stopped