# Generated by Django 6.0.4 on 2026-04-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_discount_tax_order_orderitem_order_item_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
